# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_app_seg_params.ui'
#
# Created: Thu Aug 17 11:41:13 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.segResult = GraphicsView(self.centralwidget)
        self.segResult.setEnabled(True)
        self.segResult.setMinimumSize(QtCore.QSize(600, 0))
        self.segResult.setObjectName("segResult")
        self.horizontalLayout_4.addWidget(self.segResult)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.spatialr = QtWidgets.QLabel(self.centralwidget)
        self.spatialr.setObjectName("spatialr")
        self.verticalLayout.addWidget(self.spatialr)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slider_spatialr = QtWidgets.QSlider(self.centralwidget)
        self.slider_spatialr.setMinimum(2)
        self.slider_spatialr.setMaximum(25)
        self.slider_spatialr.setProperty("value", 16)
        self.slider_spatialr.setOrientation(QtCore.Qt.Horizontal)
        self.slider_spatialr.setObjectName("slider_spatialr")
        self.horizontalLayout.addWidget(self.slider_spatialr)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMinimum(2)
        self.spinBox.setMaximum(25)
        self.spinBox.setProperty("value", 16)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ranger = QtWidgets.QLabel(self.centralwidget)
        self.ranger.setObjectName("ranger")
        self.verticalLayout_2.addWidget(self.ranger)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slider_ranger = QtWidgets.QSlider(self.centralwidget)
        self.slider_ranger.setMinimum(2)
        self.slider_ranger.setMaximum(25)
        self.slider_ranger.setProperty("value", 10)
        self.slider_ranger.setOrientation(QtCore.Qt.Horizontal)
        self.slider_ranger.setObjectName("slider_ranger")
        self.horizontalLayout_2.addWidget(self.slider_ranger)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setMinimum(2)
        self.spinBox_2.setMaximum(25)
        self.spinBox_2.setProperty("value", 10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Numberofclasses = QtWidgets.QLabel(self.centralwidget)
        self.Numberofclasses.setObjectName("Numberofclasses")
        self.verticalLayout_3.addWidget(self.Numberofclasses)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.slider_classes = QtWidgets.QSlider(self.centralwidget)
        self.slider_classes.setMinimum(2)
        self.slider_classes.setMaximum(10)
        self.slider_classes.setProperty("value", 4)
        self.slider_classes.setOrientation(QtCore.Qt.Horizontal)
        self.slider_classes.setObjectName("slider_classes")
        self.horizontalLayout_3.addWidget(self.slider_classes)
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setMinimum(2)
        self.spinBox_3.setMaximum(10)
        self.spinBox_3.setProperty("value", 4)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 594, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.slider_spatialr.valueChanged['int'].connect(self.spinBox.setValue)
        self.slider_ranger.valueChanged['int'].connect(self.spinBox_2.setValue)
        self.slider_classes.valueChanged['int'].connect(self.spinBox_3.setValue)
        self.spinBox.valueChanged['int'].connect(self.slider_spatialr.setValue)
        self.spinBox_2.valueChanged['int'].connect(self.slider_ranger.setValue)
        self.spinBox_3.valueChanged['int'].connect(self.slider_classes.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.spatialr.setText(_translate("MainWindow", "Spatialr"))
        self.ranger.setText(_translate("MainWindow", "Ranger"))
        self.Numberofclasses.setText(_translate("MainWindow", "Number of classes"))
        self.slider_classes.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>test</p></body></html>"))

from pyqtgraph import GraphicsView
